# The discovery of transcription factor binding sites in DNA

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests

In [3]:
SEQUENCES_URL = 'https://raw.githubusercontent.com/abidlabs/deep-learning-genomics-primer/master/sequences.txt'
sequences = requests.get(SEQUENCES_URL).text.split('\n')
sequences = list(filter(None, sequences))

pd.DataFrame(sequences, index=np.arange(1, len(sequences) +1), columns=['Sequences']).head()

,Sequences
1,CCGAGGGCTATGGTTTGGAAGTTAGAACCCTGGGGCTTCTCGCGGA...
2,GAGTTTATATGGCGCGAGCCTAGTGGTTTTTGTACTTGTTTGTCGC...
3,GATCAGTAGGGAAACAAACAGAGGGCCCAGCCACATCTAGCAGGTA...
4,GTCCACGACCGAACTCCCACCTTGACCGCAGAGGTACCACCAGAGC...
5,GGCGACCGAACTCCAACTAGAACCTGCATAACTGGCCTGGGAGATA...


Most deep learning algorithms accept data in the form of vectors of matrics (or more generally, tensors)

To get each DNA sequence in the form of a matrix, we use one-hot encoding, which encodes every base in a sequqnce in the form of a 4-dimensional vector, with a separate dimension for each base. We place a '1' in the dimension corresponding to the base found in the DNA sequence, and '0's in all other slots. We then concatenate these 4-dimensional vectors together along the bases in the sequence to form a matrix.

In [5]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [6]:
integer_encoder = LabelEncoder() # The LabelEncoder encodes a sequence of bases as a sequence of integers
one_hot_encoder = OneHotEncoder(categories='auto') # The OneHotEncoder converts an array of integers to a sparse matrix where each row corresponds to one possible value of each feature

input_features = []

for sequence in sequences:
    integer_encoded = integer_encoder.fit_transform(list(sequence))
    integer_encoded = np.array(integer_encoded).reshape(-1,1)
    one_hot_encoded = one_hot_encoder.fit_transform(integer_encoded)
    input_features.append(one_hot_encoded.toarray())


np.set_printoptions(threshold=40)
input_features = np.stack(input_features)
print("Example sequence\n-----------------------")
print('DNA Sequence #1:\n',sequences[0][:10],'...',sequences[0][-10:])
print('One hot encoding of Sequence #1:\n',input_features[0].T)

Example sequence
-----------------------
DNA Sequence #1:
 CCGAGGGCTA ... CGCGGACACC
One hot encoding of Sequence #1:
 [[0. 0. 0. ... 1. 0. 0.]
 [1. 1. 0. ... 0. 1. 1.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [7]:
integer_encoder

LabelEncoder()

In [11]:
integer_encoded = integer_encoder.fit_transform(list(sequence))
integer_encoded

array([0, 0, 3, ..., 2, 0, 1])

In [12]:
integer_encoded = np.array(integer_encoded).reshape(-1,1)
integer_encoded

array([[0],
       [0],
       [3],
       ...,
       [2],
       [0],
       [1]])

In [13]:
one_hot_encoded = one_hot_encoder.fit_transform(integer_encoded)
one_hot_encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 50 stored elements and shape (50, 4)>

In [14]:
one_hot_encoded.toarray()

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       ...,
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [16]:
input_features[0].T

array([[0., 0., 0., ..., 1., 0., 0.],
       [1., 1., 0., ..., 0., 1., 1.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

Labels:

'1' indicates that a protein bound to the sequence

'0' indicates that the protein did not


In [17]:
LABELS_URL = 'https://raw.githubusercontent.com/abidlabs/deep-learning-genomics-primer/master/labels.txt'

In [18]:
labels = requests.get(LABELS_URL).text.split('\n')
labels = list(filter(None, labels))

one_hot_encoder = OneHotEncoder(categories='auto')
labels = np.array(labels).reshape(-1,1)
input_labels = one_hot_encoder.fit_transform(labels).toarray()
print('Labels:\n',labels.T)
print('One-hot encoded labels:\n',input_labels.T)

Labels:
 [['0' '0' '0' ... '0' '1' '1']]
One-hot encoded labels:
 [[1. 1. 1. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 1.]]
